# themes from https://github.com/alacritty/alacritty-theme

import = ["$XDG_CONFIG_HOME/alacritty/themes/themes/gruvbox_dark.toml"]

[font]
size = 24

[font.normal]
family = "UbuntuMono Nerd Font"

[window]
decorations = "none"

[window.padding]
x = 7
y = 0